[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@hyper-evm-lib=lib/hyper-evm-lib",
    "solmate/=lib/solmate/src/",
]

[rpc_endpoints]
hyperevm = "${HYPEREVM_TESTNET_RPC}"
hyperevm-mainnet = "${HYPEREVM_MAINNET_RPC}"

[etherscan]
hyperevm = { key = "${HYPEREVM_ETHERSCAN_API_KEY}" }